### PR TITLE
[Fix] Error with opening project settings

### LINKED ISSUE #237: Don't change div.project-add-catcher for projects that don't have a catcher attached
When you go to the project settings from project that doesn't have events, the div.project-add-catcher changes to div.project-overview
изображение

### LINKED ISSUE #381: Как пользователь, я хочу иметь возможность открыть настройки проекта, чтобы изменить их
| Дано | Когда | Тогда |
| ----- | ------ | ------ | 
| Открытие настроек проекта | Кэтчер ошибок отсутствует | Открывать настройки проекта |

На данный момент при открытии настроек проекта ничего не происходит, в консоли ошибки:
image

### PR DESCRIPTION
**Pull request by ilyamore88**
Closes #237 
Closes #381

### CODE REVIEW

File: src/components/project/Overview.vue [hunk 1]
```diff
@@ -168,6 +171,18 @@ export default {
   async created() {
     this.noMoreEvents = await this.$store.dispatch(FETCH_RECENT_EVENTS, { projectId: this.projectId });
 
+    const latestEvent = this.$store.getters.getLatestEvent(this.projectId);
+
+    /**
+     * Redirect to add catcher if there isn't a lat event
```
Comment (nikmel2803) [inline src/components/project/Overview.vue:177]:
```suggestion
     * Redirect to the "add catcher" page if there are no events
```

**Review by nikmel2803 — APPROVED** [review]

**Review by talyguryn — APPROVED** [review]
