### PR TITLE
Fix/auto prolongation bug

### LINKED ISSUE #456: As user I want to see an understandable notify when I missed to check the last Autoprolongation checkbox
For now, it always tells about payment agreement

image

### PR DESCRIPTION
**Pull request by robonetphy**
resolves #456

### CODE REVIEW

File: src/components/modals/PaymentDetailsDialog.vue [hunk 1]
```diff
@@ -497,11 +505,29 @@ export default Vue.extend({
...
+           }
+           if(!this.isAcceptedChargingEveryMonth){
+              notifier.show({
+                message: this.$t('billing.paymentDetails.didNotAcceptChargingEveryMonth') as string,
+                style: 'error',
+                time: 5000,
+              });             
+           }
+        }
+        else{
```
Comment (neSpecc) [inline src/components/modals/PaymentDetailsDialog.vue:524]: pls lint the code via ESLint

Comment (robonetphy) [reply src/components/modals/PaymentDetailsDialog.vue:524]: @neSpecc,  there is no lint in this file.
image

**Review by GeekaN2 — APPROVED** [review]
I'll fix the linter in another request

**Review by neSpecc — APPROVED** [review]
